<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="TUnit" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" />
        <PackageReference Include="Microsoft.Extensions.Logging" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\Loom.Handlers\Loom.Handlers.csproj" />
    </ItemGroup>

</Project>
