<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="TUnit" />
        <PackageReference Include="NetArchTest.Rules" />
        <PackageReference Include="CodeByDylan.Loom.Entities" />
    </ItemGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\src\MyApp.Worker\MyApp.Worker.csproj" />
    </ItemGroup>

</Project>
